export enum CluedoExceptionType {
    // Player & user
    USER_NOT_FOUND,
    PLAYER_NOT_FOUND,
    PLAYER_NOT_IN_LOBBY,
    PLAYER_NOT_HOST,
    PLAYER_USER_NOT_LINKED,
    USERNAME_EXISTS,
    EMAIL_EXISTS,
    PLAYER_ALREADY_IN_LOBBY,

    // Lobby
    CLUEDO_NOT_FOUND,
    CHARACTERTYPE_TAKEN,
    LOBBY_NAME_EMPTY,
    LOBBY_TURN_DURATION_TOO_SHORT,
    LOBBY_MAX_PLAYERS_INVALID,
    LOBBY_START_PLAYER_COUNT,
    LOBBY_FULL,
    GAME_ALREADY_STARTED,

    // Game
    CATEGORY_NOT_EXIST,
    SCENE_NOT_ACCUSATION,
    SCENE_NOT_SUGGESTION,
    NOTEBOOK_NOT_FOUND,

    // Board
    BOARD_NOT_FOUND,

    // Success
    SUCCESS,

    UNEXPECTED,

}